export const INCREMENT = "INCREMENT";
export const INCREMENT_ADD = "INCREMENT_ADD";
export const DECREMENT = "DECREMENT";
export const DECREMENT_SUBSTRATION = "DECREMENT_SUBSTRATION";
export const STORE_RESULT = "STORE_RESULT";
export const DELETE_RESULT = "DELETE_RESULT";
